name: Publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - id: build-and-push
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          file: Dockerfile
          tags: ${{ secrets.DOCKERHUB_REPO }}:latest
          build-args: |
            VITE_FIREBASE_CONFIG=${{ secrets.VITE_FIREBASE_CONFIG }}
            VITE_API_URL=${{ secrets.VITE_API_URL }}
            VITE_MAPBOX_TOKEN=${{ secrets.VITE_MAPBOX_TOKEN }}

      - id: deploy
        name: Deploy
        run: |
          curl --location '${{ secrets.DEPLOY_URL }}' \
            --header 'Accept: application/vnd.github+json' \
            --header 'X-GitHub-Api-Version: 2022-11-28' \
            --header 'Content-Type: application/json' \
            --header 'Authorization: ${{ secrets.DEPLOY_AUTH }}' \
            --data '${{ secrets.DEPLOY_PAYLOAD }}'
